@ApiGatewayLocalHostAddress = http://localhost:5069

GET {{ApiGatewayLocalHostAddress}}/api/compet-svc/competition
Accept: application/json

###


GET {{ApiGatewayLocalHostAddress}}/api/regstr-svc/competitors
Accept: application/json

###
