
@ApiGatewayAzureHostAddress = https://ca-cloudtrack-apigw-demo.happyriver-9b282881.westeurope.azurecontainerapps.io

GET {{ApiGatewayAzureHostAddress}}/api/compet-svc/competition
Accept: application/json

###

POST {{ApiGatewayAzureHostAddress}}/api/compet-svc/competition
Content-Type: application/json
Accept: application/json


{
  "name": "Warsaw Marathon 2025",
  "startAt": "2025-09-04T09:00:00.000Z",
  "distance": {
    "amount": 42.195,
    "unit": "Kilometers"
  },
  "place": {
    "city": "Warsaw",
    "latitude": 0,
    "longitute": 0
  },
  "maxCompetitors": 4500
}

###

POST {{ApiGatewayAzureHostAddress}}/api/compet-svc/competition/e0aa988f-05ab-4d06-8077-70e34dbaefb1/Registration/Open
#Content-Type: application/json
Accept: application/json

###

GET {{ApiGatewayAzureHostAddress}}/api/regstr-svc/competitor/e0aa988f-05ab-4d06-8077-70e34dbaefb1
Accept: application/json

###

POST {{ApiGatewayAzureHostAddress}}/api/regstr-svc/registration
Content-Type: application/json
Accept: application/json


{
  "competitionId": "e0aa988f-05ab-4d06-8077-70e34dbaefb1",
  "firstName": "John3",
  "lastName": "Smith3",
  "birthDate": "1980-01-28T17:04:21.539Z",
  "city": "London",
  "phoneNumber": "123123123",
  "contactPersonNumber": "345345345"
}

###
